#!/bin/bash

# PRP Directory Configuration Loader
# This script provides functions to load and resolve PRP and research directory paths
# Used by generate-prp and execute-prp commands

# Default configuration
DEFAULT_PRP_DIR="./PRPs"
DEFAULT_RESEARCH_DIR="./research"
CONFIG_FILE="$HOME/.claude/config/prp-storage.conf"

# Load configuration from file if it exists
load_prp_config() {
    local prp_dir="$DEFAULT_PRP_DIR"
    local research_dir="$DEFAULT_RESEARCH_DIR"
    
    # Load from config file if it exists
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE" 2>/dev/null || true
        # Use loaded values if they exist
        if [ -n "$PRP_DIR" ]; then
            prp_dir="$PRP_DIR"
        fi
        if [ -n "$RESEARCH_DIR" ]; then
            research_dir="$RESEARCH_DIR"
        fi
    fi
    
    # Override with environment variables if set
    if [ -n "$CLAUDE_PRP_BASE_DIR" ]; then
        prp_dir="$CLAUDE_PRP_BASE_DIR/PRPs"
        research_dir="$CLAUDE_PRP_BASE_DIR/research"
    fi
    
    if [ -n "$CLAUDE_PRP_DIR" ]; then
        prp_dir="$CLAUDE_PRP_DIR"
    fi
    
    if [ -n "$CLAUDE_RESEARCH_DIR" ]; then
        research_dir="$CLAUDE_RESEARCH_DIR"
    fi
    
    # Return the resolved directories
    echo "PRP_DIR=$prp_dir"
    echo "RESEARCH_DIR=$research_dir"
}

# Resolve a PRP file path using configuration
resolve_prp_path() {
    local input_path="$1"
    local prp_dir_override="$2"
    
    # If absolute path, use as-is
    if [[ "$input_path" == /* ]]; then
        echo "$input_path"
        return
    fi
    
    # Load configuration
    eval "$(load_prp_config)"
    
    # Use override if provided
    if [ -n "$prp_dir_override" ]; then
        PRP_DIR="$prp_dir_override"
    fi
    
    # Check if file exists in configured PRP directory
    if [ -f "$PRP_DIR/$input_path" ]; then
        echo "$PRP_DIR/$input_path"
        return
    fi
    
    # Check if file exists in current directory
    if [ -f "./$input_path" ]; then
        echo "./$input_path"
        return
    fi
    
    # Return the configured path even if file doesn't exist (for error handling)
    echo "$PRP_DIR/$input_path"
}

# Create directories if they don't exist
ensure_directories() {
    eval "$(load_prp_config)"
    
    # Create PRP directory
    if [ ! -d "$PRP_DIR" ]; then
        mkdir -p "$PRP_DIR"
        echo "Created PRP directory: $PRP_DIR"
        
        # Create templates directory if it doesn't exist
        if [ ! -d "$PRP_DIR/templates" ]; then
            mkdir -p "$PRP_DIR/templates"
            echo "Created templates directory: $PRP_DIR/templates"
        fi
    fi
    
    # Create research directory
    if [ ! -d "$RESEARCH_DIR" ]; then
        mkdir -p "$RESEARCH_DIR"
        echo "Created research directory: $RESEARCH_DIR"
    fi
}

# Save configuration to file
save_prp_config() {
    local prp_dir="$1"
    local research_dir="$2"
    local base_dir="$3"
    
    # Create config directory if it doesn't exist
    mkdir -p "$(dirname "$CONFIG_FILE")"
    
    # Write configuration
    cat > "$CONFIG_FILE" << EOF
# PRP Storage Configuration
# This file is auto-generated by /config-prp-storage command

CREATED_DATE="$(date '+%Y-%m-%d %H:%M:%S')"
LAST_UPDATED="$(date '+%Y-%m-%d %H:%M:%S')"

EOF
    
    if [ -n "$base_dir" ]; then
        echo "PRP_BASE_DIR=\"$base_dir\"" >> "$CONFIG_FILE"
        echo "PRP_DIR=\"$base_dir/PRPs\"" >> "$CONFIG_FILE"  
        echo "RESEARCH_DIR=\"$base_dir/research\"" >> "$CONFIG_FILE"
    else
        echo "PRP_DIR=\"$prp_dir\"" >> "$CONFIG_FILE"
        echo "RESEARCH_DIR=\"$research_dir\"" >> "$CONFIG_FILE"
    fi
    
    echo "Configuration saved to: $CONFIG_FILE"
}

# Show current configuration
show_prp_config() {
    echo "PRP Directory Configuration:"
    echo "============================="
    
    eval "$(load_prp_config)"
    
    echo "PRP Directory: $PRP_DIR"
    echo "Research Directory: $RESEARCH_DIR"
    echo ""
    
    if [ -f "$CONFIG_FILE" ]; then
        echo "Configuration file: $CONFIG_FILE"
        if grep -q "CREATED_DATE" "$CONFIG_FILE"; then
            echo "Created: $(grep CREATED_DATE "$CONFIG_FILE" | cut -d'=' -f2 | tr -d '"')"
            echo "Updated: $(grep LAST_UPDATED "$CONFIG_FILE" | cut -d'=' -f2 | tr -d '"')"
        fi
    else
        echo "Configuration file: Not configured (using defaults)"
    fi
    
    echo ""
    echo "Environment Variables:"
    echo "CLAUDE_PRP_BASE_DIR: ${CLAUDE_PRP_BASE_DIR:-not set}"
    echo "CLAUDE_PRP_DIR: ${CLAUDE_PRP_DIR:-not set}"
    echo "CLAUDE_RESEARCH_DIR: ${CLAUDE_RESEARCH_DIR:-not set}"
}

# Reset configuration to defaults
reset_prp_config() {
    if [ -f "$CONFIG_FILE" ]; then
        rm "$CONFIG_FILE"
        echo "Configuration file removed: $CONFIG_FILE"
    else
        echo "No configuration file found to remove"
    fi
    echo "Reset to defaults (current working directory: ./PRPs, ./research)"
}

# Main command handler
case "${1:-}" in
    "load")
        load_prp_config
        ;;
    "resolve")
        resolve_prp_path "$2" "$3"
        ;;
    "ensure")
        ensure_directories
        ;;
    "save")
        save_prp_config "$2" "$3" "$4"
        ;;
    "show")
        show_prp_config
        ;;
    "reset")
        reset_prp_config
        ;;
    *)
        echo "PRP Configuration Loader"
        echo "Usage: $0 {load|resolve|ensure|save|show|reset}"
        echo ""
        echo "Commands:"
        echo "  load                          - Load and display current configuration"
        echo "  resolve <file> [prp_dir]     - Resolve PRP file path using configuration"
        echo "  ensure                       - Create directories if they don't exist"
        echo "  save <prp_dir> <research_dir> [base_dir] - Save configuration"
        echo "  show                         - Show current configuration"
        echo "  reset                        - Reset to defaults"
        ;;
esac